services:
  database:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=expense
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgressql/data
  server:
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DB_HOST=database
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=expense
    depends_on:
      - database
  # frontend:
  #   build: ./client
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ./client:/client
  #     - /client/node_modules
  #   depends_on:
  #     - server
  #   environment:
  #     CHOKIDAR_USEPOLLING: "true"  
volumes:
  postgres-data:
